Repository humanmade/altis-core, pull requests merged in 2022-02, with the labels that each got.

#395 Update Travis file reference to 9b482cb
  .travis.yml
Labels: backport v10-branch

#402 Add upgrade prompts when not on the latest version
  inc/upgrades/namespace.php
Labels: backport v7-branch, backport v8-branch, backport v9-branch, backport v10-branch

#408 [Backport v9-branch] Add upgrade prompts when not on the latest version
  inc/upgrades/namespace.php
Labels: backport v7-branch, backport v8-branch

#406 Skip upgrade notice if on a dev branch
  inc/upgrades/namespace.php
Labels: backport v7-branch, backport v8-branch, backport v9-branch, backport v10-branch
