Repository humanmade/altis-core, pull requests merged in 2022-03, with the labels that each got.

#419 Global Content Repository urls
  docs/global-content-repository.md
Labels: backport v8-branch, backport v9-branch, backport v10-branch

#424 Correctly hash for automatic IDs
  inc/telemetry/namespace.php
Labels: backport v10-branch

#442 Fix Composer v2 operation type usage
  inc/composer/class-plugin.php
Labels: backport v6-branch, backport v7-branch, backport v8-branch, backport v9-branch, backport v10-branch
